services:
  data-store:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
  data-store-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config1
    ports:
      - "8070:8070"
      - "8071:8071"
      - "8072:8072"

  data-store-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        config: config2
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"

networks:
  default:
    name: data-store-network